const types = Object.freeze({
  SET_GAME_STATE: "SET_GAME_STATE",
  ADD_CARD_TO_PLAYER: "ADD_CARD_TO_PLAYER",
  ADD_CARD_TO_AI: "ADD_CARD_TO_AI",
  REMOVE_CARD_FROM_PLAYER: "REMOVE_CARD_TO_PLAYER",
  REMOVE_CARD_FROM_AI: "REMOVE_CARD_FROM_AI",
});

export default types;
